import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Homepage
    'home.welcome': 'Welcome to Modern Education Center',
    'home.choosePortal': 'Choose Your Portal',
    'home.studentPortal': 'Student Portal',
    'home.teacherPortal': 'Teacher Portal',
    'home.adminPortal': 'Admin Portal',
    'home.studentDesc': 'Register, select courses, and track your progress',
    'home.teacherDesc': 'Manage students, mark attendance, and upload lessons',
    'home.adminDesc': 'View analytics, manage payments, and oversee operations',
    'home.copyright': '© 2024 Modern Education Institute of Languages. All rights reserved.',
    'home.instituteName': 'Modern Education Institute of Languages',
    'home.selectLanguage': 'Select Language',
    
    // Student Portal
    'student.signup': 'Student Registration',
    'student.signup.subtitle': 'Create your account to get started',
    'student.fullNameAr': 'Full Name (Arabic)',
    'student.fullNameEn': 'Full Name (English)',
    'student.phone': 'Phone Number',
    'student.phoneSecondary': 'Phone Number (Secondary)',
    'student.email': 'Email Address',
    'student.nationalId': 'National ID / Iqama',
    'student.backHome': 'Back to Home',
    'student.next': 'Next',
    'student.fillRequired': 'Please fill in all required fields',
    'student.courseSelection': 'Course Selection',
    'student.back': 'Back',
    'student.englishLevel': 'English Program Level',
    'student.selectLevel': 'Select your level',
    'student.classType': 'Class Type / Other Languages',
    'student.selectClassType': 'Select class type',
    'student.courseInfo': 'Course Information',
    'student.courseInfoDesc': 'Each English course consists of 8 parts. Your progress will be tracked throughout the program.',
    'student.selectBothError': 'Please select both program level and class type',
    'student.branchSelection': 'Branch Selection',
    'student.selectBranch': 'Branch',
    'student.selectBranchError': 'Please select a branch',
    'student.paymentMethod': 'Payment Method',
    'student.selectPayment': 'Select Payment Method',
    'student.selectPaymentError': 'Please select a payment method',
    'student.paymentTerms': 'Payment Terms',
    'student.paymentTermsDesc': 'Payment confirmation will be processed within 24 hours. You will receive access to your course materials once payment is verified.',
    'student.confirmSubscribe': 'Confirm & Subscribe',
    'student.registrationSuccess': 'Registration completed successfully!',
    'student.myCourse': 'My Course',
    'student.courseLevel': 'Course Level',
    'student.program': 'Program',
    'student.classTypeLabel': 'Class Type',
    'student.subscriptionStatus': 'Subscription Status',
    'student.active': 'Active',
    'student.branchLocation': 'Branch Location',
    'student.nextPayment': 'Next Payment',
    'student.dailyAttendance': 'Daily Attendance',
    'student.days': 'Days',
    'student.completePart': 'Complete a part to mark daily attendance',
    'student.courseProgress': 'Course Progress',
    'student.completedParts': 'Completed Parts',
    'student.keepGoing': 'Keep going!',
    'student.partsRemaining': 'parts remaining',
    'student.congratulations': '🎉 Congratulations! You\'ve completed the course!',
    'student.curriculum': 'Course Curriculum',
    'student.completed': 'Completed',
    'student.inProgress': 'In Progress',
    'student.locked': 'Locked',
    'student.available': 'Available',
    'student.lessons': 'lessons',
    'student.attend': 'Attend',
    'student.completedCheck': 'Completed ✓',
    'student.attendanceMarked': 'Lesson attendance marked',
    'student.attendanceAlready': 'Attendance already marked for this lesson',
    'student.partCompleted': 'completed! Daily attendance marked.',
    'student.part': 'Part',
    'student.home': 'Home',
    
    // Course Parts
    'course.part1.title': 'Introduction & Basics',
    'course.part2.title': 'Grammar Fundamentals',
    'course.part3.title': 'Everyday Conversations',
    'course.part4.title': 'Expanding Vocabulary',
    'course.part5.title': 'Intermediate Grammar',
    'course.part6.title': 'Communication Skills',
    'course.part7.title': 'Advanced Topics',
    'course.part8.title': 'Final Review & Assessment',
    
    'course.lesson1': 'Welcome & Course Overview',
    'course.lesson2': 'Alphabet & Pronunciation',
    'course.lesson3': 'Basic Greetings',
    'course.lesson4': 'Numbers 1-100',
    'course.lesson5': 'Present Simple Tense',
    'course.lesson6': 'Articles (a, an, the)',
    'course.lesson7': 'Personal Pronouns',
    'course.lesson8': 'Basic Sentence Structure',
    'course.lesson9': 'Shopping & Money',
    'course.lesson10': 'At the Restaurant',
    'course.lesson11': 'Asking for Directions',
    'course.lesson12': 'Making Plans',
    'course.lesson13': 'Family & Relationships',
    'course.lesson14': 'Hobbies & Interests',
    'course.lesson15': 'Weather & Seasons',
    'course.lesson16': 'Jobs & Professions',
    'course.lesson17': 'Past Simple Tense',
    'course.lesson18': 'Future Forms',
    'course.lesson19': 'Comparative & Superlative',
    'course.lesson20': 'Modal Verbs',
    'course.lesson21': 'Email Writing',
    'course.lesson22': 'Phone Conversations',
    'course.lesson23': 'Presentations Basics',
    'course.lesson24': 'Business Meetings',
    'course.lesson25': 'Conditional Sentences',
    'course.lesson26': 'Passive Voice',
    'course.lesson27': 'Reported Speech',
    'course.lesson28': 'Phrasal Verbs',
    'course.lesson29': 'Comprehensive Review',
    'course.lesson30': 'Practice Test',
    'course.lesson31': 'Final Exam',
    'course.lesson32': 'Certificate Award',
    
    // Branch names
    'branch.online': 'Online Classes',
    'branch.onlineDesc': 'Learn from anywhere with our virtual classrooms',
    'branch.dammam': 'Dammam Branch',
    'branch.dammamDesc': 'Main campus in Dammam',
    'branch.dhahran': 'Dhahran Branch',
    'branch.dhahranDesc': 'Located in Dhahran',
    'branch.khobar': 'Khobar Branch',
    'branch.khobarDesc': 'Located in Khobar',
    
    // Payment methods
    'payment.card': 'Card',
    'payment.cardDesc': 'Credit/Debit Card - Visa, Mastercard, Mada',
    'payment.cash': 'Cash',
    'payment.cashDesc': 'Pay in cash at branch',
    'payment.cardCash': 'Card/Cash',
    'payment.cardCashDesc': 'Pay with card or cash',
    'payment.transfer': 'Bank Transfer',
    'payment.transferDesc': 'Direct bank transfer',
    'payment.tamara': 'Tamara',
    'payment.tamaraDesc': 'Split into installments',
    'payment.tabby': 'Tabby',
    'payment.tabbyDesc': 'Buy now, pay later',
    'payment.stcpay': 'Stcpay',
    'payment.stcpayDesc': 'STC Pay digital wallet',
    
    // Teacher Portal
    'teacher.login': 'Teacher Login',
    'teacher.email': 'Teacher Email',
    'teacher.password': 'Password',
    'teacher.loginButton': 'Login to Teacher Portal',
    'teacher.dashboard': 'Teacher Dashboard',
    'teacher.backHome': 'Back to Home',
    'teacher.logout': 'Logout',
    'teacher.totalStudents': 'Total Students',
    'teacher.activeClasses': 'Active Classes',
    'teacher.pendingAttendance': 'Pending Attendance',
    'teacher.markAttendance': 'Mark Attendance',
    'teacher.uploadLessons': 'Upload Lessons',
    'teacher.createQuiz': 'Create Quiz',
    'teacher.myStudents': 'My Students',
    'teacher.course': 'Course',
    'teacher.progress': 'Progress',
    'teacher.courseProgress': 'Course Progress',
    'teacher.parts': 'parts',
    'teacher.quizTitle': 'Quiz Title',
    'teacher.quizTitlePlaceholder': 'Enter quiz title',
    'teacher.numberOfQuestions': 'Number of Questions',
    'teacher.question': 'Question',
    'teacher.questionText': 'Enter question text',
    'teacher.answers': 'Answer Options',
    'teacher.answer': 'Answer',
    'teacher.addQuestion': 'Add Question',
    'teacher.saveQuiz': 'Save Quiz',
    'teacher.quizCreated': 'Quiz Created Successfully!',
    'teacher.quizCreatedDesc': 'Your quiz has been created',
    'teacher.questionType': 'Question Type',
    'teacher.multipleChoice': 'Multiple Choice',
    'teacher.longAnswer': 'Long Answer (Essay)',
    'teacher.imageQuestion': 'Image',
    'teacher.videoQuestion': 'Video',
    'teacher.audioQuestion': 'Audio',
    'teacher.uploadFile': 'Upload File',
    'teacher.uploading': 'Uploading...',
    'teacher.fileUploaded': 'File Uploaded',
    'teacher.removeFile': 'Remove File',
    'teacher.correctAnswer': 'Correct Answer',
    'teacher.markCorrect': 'Mark as Correct',
    'teacher.points': 'Points',
    'teacher.pointsPlaceholder': 'Enter points for this question',
    'teacher.lessonTitle': 'Lesson Title',
    'teacher.lessonTitlePlaceholder': 'Enter lesson title',
    'teacher.selectFile': 'Select File',
    'teacher.selectedFile': 'Selected file',
    'teacher.uploadLesson': 'Upload Lesson',
    'teacher.uploadedLessons': 'Uploaded Lessons',
    'teacher.lessonUploaded': 'Lesson Uploaded Successfully!',
    'teacher.lessonUploadedDesc': 'Lesson uploaded',
    'teacher.error': 'Error',
    'teacher.fillAllFields': 'Please fill all fields and select a file',
    'teacher.studentName': 'Student Name',
    'teacher.status': 'Status',
    'teacher.present': 'Present',
    'teacher.absent': 'Absent',
    'teacher.saveAttendance': 'Save Attendance',
    'teacher.attendanceSaved': 'Attendance Saved Successfully!',
    'teacher.attendanceSavedDesc': 'Attendance has been recorded',
    'teacher.loginError': 'Please enter email and password',
    'teacher.loginSuccess': 'Teacher login successful!',
    'teacher.myQuizzes': 'My Quizzes',
    'teacher.viewQuizzes': 'View Quizzes',
    'teacher.quizzes': 'Quizzes',
    'teacher.attempts': 'Attempts',
    'teacher.viewAttempts': 'View Attempts',
    'teacher.noQuizzes': 'No quizzes created yet',
    'teacher.createFirstQuiz': 'Create your first quiz',
    'teacher.studentAnswers': 'Student Answers',
    'teacher.submittedAt': 'Submitted At',
    'teacher.notSubmitted': 'Not Submitted',
    'teacher.viewDetails': 'View Details',
    'teacher.gradeQuiz': 'Grade Quiz',
    'teacher.graded': 'Graded',
    'teacher.notGraded': 'Not Graded',
    'teacher.grade': 'Grade',
    'teacher.feedback': 'Feedback',
    'teacher.pointsAwarded': 'Points Awarded',
    'teacher.questionFeedback': 'Question Feedback',
    'teacher.saveGrade': 'Save Grade',
    'teacher.gradedAt': 'Graded At',
    'teacher.viewAllResults': 'View All Quiz Results',
    
    // Admin Portal
    'admin.login': 'Admin Portal',
    'admin.email': 'Admin Email',
    'admin.password': 'Password',
    'admin.loginButton': 'Login to Admin Portal',
    'admin.secureAccess': 'Secure admin access only. Unauthorized access is prohibited.',
    'admin.dashboard': 'Admin Dashboard',
    'admin.backHome': 'Back to Home',
    'admin.logout': 'Logout',
    'admin.totalStudents': 'Total Students',
    'admin.totalTeachers': 'Active Teachers',
    'admin.revenue': 'Revenue (SAR)',
    'admin.activeClasses': 'Course Completion',
    'admin.studentsInfo': 'Students',
    'admin.teachersInfo': 'Teachers',
    'admin.recentRegistrations': 'Recent Registrations',
    'admin.registeredOn': 'Registered on',
    'admin.loginError': 'Please enter email and password',
    'admin.loginSuccess': 'Admin login successful!',
    'admin.exportData': 'Export Data',
    'admin.nameEn': 'Name (EN)',
    'admin.nameAr': 'Name (AR)',
    'admin.branch': 'Branch',
    'admin.payment': 'Payment',
    'admin.status': 'Status',
    'admin.assignedCourses': 'Assigned Courses',
    'admin.students': 'Students',
    'admin.paymentManagement': 'Payment Management',
    'admin.student': 'Student',
    'admin.amount': 'Amount (SAR)',
    'admin.date': 'Date',
    'admin.paid': 'Paid',
    'admin.pending': 'Pending',
    'admin.analytics': 'Analytics',
    'admin.reports': 'Reports',
    'admin.analyticsInsights': 'Analytics & Insights',
    'admin.enrollmentTrend': 'Student Enrollment Trend',
    'admin.studentPerformance': 'Student Performance',
    'admin.reportsExport': 'Reports & Export',
    'admin.studentDataReport': 'Student Data Report',
    'admin.studentDataReportDesc': 'Export complete student information including attendance and progress',
    'admin.exportCSV': 'Export CSV',
    'admin.paymentReport': 'Payment Report',
    'admin.paymentReportDesc': 'Export payment history and transaction details',
    'admin.exportPDF': 'Export PDF',
    'admin.teacherPerformanceReport': 'Teacher Performance Report',
    'admin.teacherPerformanceReportDesc': 'Export teacher statistics and student outcomes',
    'admin.analyticsSummary': 'Analytics Summary',
    'admin.analyticsSummaryDesc': 'Export comprehensive analytics and trends',
    'admin.exportSuccess': 'Export Successful!',
    'admin.exportSuccessDesc': 'Data exported via',
    'admin.shareToEmail': 'Share to Email',
    'admin.downloadCSV': 'Download CSV',
    'admin.exportToGoogleDrive': 'Export to Google Drive',
    'admin.addNewStudent': 'Add New Student',
    'admin.addPreviousStudents': 'Add Previous Students',
    'admin.viewAttendanceRecords': 'View Attendance Records',
    
    // Student cards on homepage
    'home.studentLogin': 'Student Login',
    'home.studentLoginDesc': 'Already registered? Access your course materials and track your progress',
    'home.newStudentRegistration': 'New Student Registration',
    'home.newStudentRegistrationDesc': 'First time here? Complete your registration to join our courses',
    'home.teacherLogin': 'Teacher Login',
    'home.teacherLoginDesc': 'Access your dashboard to manage students and mark attendance',
    'home.newTeacherRegistration': 'New Teacher Registration',
    'home.newTeacherRegistrationDesc': 'Join our team and start managing your classes',
    'home.administration': 'Administration',
    
    // Add Previous Student Modal
    'addPrevStudent.title': 'Add Previous Student',
    'addPrevStudent.step': 'Step',
    'addPrevStudent.of': 'of',
    'addPrevStudent.fullNameEn': 'Full Name (English)',
    'addPrevStudent.fullNameAr': 'Full Name (Arabic)',
    'addPrevStudent.phone1': 'Phone 1',
    'addPrevStudent.phone2': 'Phone 2 (Optional)',
    'addPrevStudent.email': 'Email',
    'addPrevStudent.nationalId': 'National ID / Iqama',
    'addPrevStudent.password': 'Password',
    'addPrevStudent.passwordPlaceholder': 'Enter password (min 6 characters)',
    'addPrevStudent.selectCourses': 'Select Courses (Multiple selection allowed)',
    'addPrevStudent.selected': 'Selected',
    'addPrevStudent.courses': 'course(s)',
    'addPrevStudent.selectBranch': 'Select Branch',
    'addPrevStudent.selectPaymentMethod': 'Select Payment Method',
    'addPrevStudent.addStudent': 'Add Student',
    'addPrevStudent.fillAllFields': 'Please fill all required fields',
    'addPrevStudent.passwordMinLength': 'Password must be at least 6 characters',
    'addPrevStudent.selectAtLeastOneCourse': 'Please select at least one course',
    'addPrevStudent.selectBranchError': 'Please select a branch',
    'addPrevStudent.selectPaymentError': 'Please select a payment method',
    'addPrevStudent.success': 'Previous student added successfully! Redirecting to student page...',
    'addPrevStudent.error': 'Failed to add previous student',
    'addPrevStudent.generalError': 'An error occurred',
    
    // Common messages
    'common.loading': 'Loading...',
    'common.noStudentsYet': 'No students registered yet',
    'common.noTeachersYet': 'No teachers registered yet',
    'common.notAssigned': 'Not assigned',
    
    // Student Quiz
    'student.availableQuizzes': 'Available Quizzes',
    'student.myQuizzes': 'My Quizzes',
    'student.takeQuiz': 'Take Quiz',
    'student.quizCompleted': 'Completed',
    'student.quizNotStarted': 'Not Started',
    'student.questions': 'Questions',
    'student.totalPoints': 'Total Points',
    'student.yourScore': 'Your Score',
    'student.submitQuiz': 'Submit Quiz',
    'student.selectAnswer': 'Select an answer',
    'student.writeAnswer': 'Write your answer here',
    'student.quizSubmitted': 'Quiz Submitted!',
    'student.quizSubmittedDesc': 'Your answers have been submitted successfully',
    'student.confirmSubmit': 'Are you sure you want to submit?',
    'student.cannotChangeAnswers': 'You cannot change your answers after submission',
    'student.studentAnswer': 'Student Answer',
    'student.notes': 'Notes',
    'student.myNotes': 'My Notes',
    'student.addNote': 'Add Note',
    'student.noteTitle': 'Note Title',
    'student.noteTitlePlaceholder': 'Enter note title',
    'student.noteContent': 'Note Content',
    'student.noteContentPlaceholder': 'Write your notes here...',
    'student.saveNote': 'Save Note',
    'student.editNote': 'Edit Note',
    'student.deleteNote': 'Delete Note',
    'student.noNotes': 'No notes yet',
    'student.createFirstNote': 'Create your first note',
    'student.noteSaved': 'Note Saved!',
    'student.noteSavedDesc': 'Your note has been saved successfully',
    'student.noteDeleted': 'Note Deleted!',
    'student.noteDeletedDesc': 'Your note has been deleted',
    
    // Not Found
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.returnHome': 'Return to Home',
    
    // Common
    'common.login': 'Login',
    'common.signup': 'Sign Up',
    'common.logout': 'Logout',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.created': 'Created',
    'common.back': 'Back',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Search and filters
    'search.studentsPlaceholder': 'Search students by name, phone, or ID...',
    'search.teachersPlaceholder': 'Search teachers by name, email, or courses...',
    'search.studentManagementPlaceholder': 'Search by student name, phone number, or student ID...',
    
    // Login placeholders
    'placeholder.adminEmail': 'admin@me-english.com',
    'placeholder.studentEmail': 'student@example.com',
    'placeholder.password': '••••••••',
    'placeholder.fullNameArabic': 'الاسم الكامل',
    'placeholder.fullNameEnglish': 'Full Name',
    'placeholder.phoneNumber': 'XXX XXX XXX',
    'placeholder.email': 'email@example.com',
    'placeholder.idNumber': 'ID Number',
    'placeholder.enterPassword': 'Enter password (min 8 characters)',
    'placeholder.teacherName': 'John Doe',
    'placeholder.grade': 'A+, B, 95%, etc.',
    'placeholder.courseDuration': 'Enter number of months',
    
    // Translation
    'translation.translating': 'Translating from Arabic...',
  },
  ar: {
    // Homepage
    'home.welcome': 'مرحباً بكم في مركز التعليم الحديث',
    'home.choosePortal': 'اختر بوابتك',
    'home.studentPortal': 'بوابة الطالب',
    'home.teacherPortal': 'بوابة المعلم',
    'home.adminPortal': 'بوابة الإدارة',
    'home.studentDesc': 'سجل، اختر الدورات، وتتبع تقدمك',
    'home.teacherDesc': 'إدارة الطلاب، تسجيل الحضور، ورفع الدروس',
    'home.adminDesc': 'عرض التحليلات، إدارة المدفوعات، والإشراف على العمليات',
    'home.copyright': '© 2024 المعهد الحديث للتعليم واللغات. جميع الحقوق محفوظة.',
    'home.instituteName': 'المعهد الحديث للتعليم واللغات',
    'home.selectLanguage': 'اختر اللغة',
    
    // Student Portal
    'student.signup': 'تسجيل الطالب',
    'student.signup.subtitle': 'أنشئ حسابك للبدء',
    'student.fullNameAr': 'الاسم الكامل (عربي)',
    'student.fullNameEn': 'الاسم الكامل (إنجليزي)',
    'student.phone': 'رقم الهاتف',
    'student.phoneSecondary': 'رقم الهاتف (ثانوي)',
    'student.email': 'البريد الإلكتروني',
    'student.nationalId': 'رقم الهوية / الإقامة',
    'student.backHome': 'العودة للرئيسية',
    'student.next': 'التالي',
    'student.fillRequired': 'يرجى ملء جميع الحقول المطلوبة',
    'student.courseSelection': 'اختيار الدورة',
    'student.back': 'رجوع',
    'student.englishLevel': 'مستوى برنامج اللغة الإنجليزية',
    'student.selectLevel': 'اختر مستواك',
    'student.classType': 'نوع الفصل / لغات أخرى',
    'student.selectClassType': 'اختر نوع الفصل',
    'student.courseInfo': 'معلومات الدورة',
    'student.courseInfoDesc': 'تتكون كل دورة لغة إنجليزية من 8 أجزاء. سيتم تتبع تقدمك طوال البرنامج.',
    'student.selectBothError': 'يرجى اختيار مستوى البرنامج ونوع الفصل',
    'student.branchSelection': 'اختيار الفرع',
    'student.selectBranch': 'اختر الفرع المفضل لديك',
    'student.selectBranchError': 'يرجى اختيار فرع',
    'student.paymentMethod': 'طريقة الدفع',
    'student.selectPayment': 'اختر طريقة الدفع',
    'student.selectPaymentError': 'يرجى اختيار طريقة الدفع',
    'student.paymentTerms': 'شروط الدفع',
    'student.paymentTermsDesc': 'سيتم معالجة تأكيد الدفع خلال 24 ساعة. ستحصل على وصول إلى مواد الدورة بمجرد التحقق من الدفع.',
    'student.confirmSubscribe': 'تأكيد والاشتراك',
    'student.registrationSuccess': 'تم التسجيل بنجاح!',
    'student.myCourse': 'دورتي',
    'student.courseLevel': 'مستوى الدورة',
    'student.program': 'البرنامج',
    'student.classTypeLabel': 'نوع الفصل',
    'student.subscriptionStatus': 'حالة الاشتراك',
    'student.active': 'نشط',
    'student.branchLocation': 'موقع الفرع',
    'student.nextPayment': 'الدفعة القادمة',
    'student.dailyAttendance': 'الحضور اليومي',
    'student.days': 'أيام',
    'student.completePart': 'أكمل جزءاً لتسجيل الحضور اليومي',
    'student.courseProgress': 'تقدم الدورة',
    'student.completedParts': 'الأجزاء المكتملة',
    'student.keepGoing': 'استمر!',
    'student.partsRemaining': 'أجزاء متبقية',
    'student.congratulations': '🎉 تهانينا! لقد أكملت الدورة!',
    'student.curriculum': 'منهج الدورة',
    'student.completed': 'مكتمل',
    'student.inProgress': 'قيد التنفيذ',
    'student.locked': 'مقفل',
    'student.available': 'متاح',
    'student.lessons': 'دروس',
    'student.attend': 'حضور',
    'student.completedCheck': 'مكتمل ✓',
    'student.attendanceMarked': 'تم تسجيل حضور الدرس',
    'student.attendanceAlready': 'تم تسجيل الحضور لهذا الدرس مسبقاً',
    'student.partCompleted': 'مكتمل! تم تسجيل الحضور اليومي.',
    'student.part': 'الجزء',
    'student.home': 'الرئيسية',
    
    // Course Parts
    'course.part1.title': 'المقدمة والأساسيات',
    'course.part2.title': 'أساسيات القواعد',
    'course.part3.title': 'المحادثات اليومية',
    'course.part4.title': 'توسيع المفردات',
    'course.part5.title': 'القواعد المتوسطة',
    'course.part6.title': 'مهارات التواصل',
    'course.part7.title': 'المواضيع المتقدمة',
    'course.part8.title': 'المراجعة النهائية والتقييم',
    
    'course.lesson1': 'الترحيب ونظرة عامة',
    'course.lesson2': 'الأبجدية والنطق',
    'course.lesson3': 'التحيات الأساسية',
    'course.lesson4': 'الأرقام 1-100',
    'course.lesson5': 'المضارع البسيط',
    'course.lesson6': 'أدوات التعريف',
    'course.lesson7': 'الضمائر الشخصية',
    'course.lesson8': 'تركيب الجملة الأساسي',
    'course.lesson9': 'التسوق والمال',
    'course.lesson10': 'في المطعم',
    'course.lesson11': 'السؤال عن الاتجاهات',
    'course.lesson12': 'وضع الخطط',
    'course.lesson13': 'العائلة والعلاقات',
    'course.lesson14': 'الهوايات والاهتمامات',
    'course.lesson15': 'الطقس والفصول',
    'course.lesson16': 'الوظائف والمهن',
    'course.lesson17': 'الماضي البسيط',
    'course.lesson18': 'صيغ المستقبل',
    'course.lesson19': 'المقارنة والتفضيل',
    'course.lesson20': 'الأفعال المساعدة',
    'course.lesson21': 'كتابة البريد الإلكتروني',
    'course.lesson22': 'المحادثات الهاتفية',
    'course.lesson23': 'أساسيات العروض التقديمية',
    'course.lesson24': 'الاجتماعات التجارية',
    'course.lesson25': 'الجمل الشرطية',
    'course.lesson26': 'المبني للمجهول',
    'course.lesson27': 'الكلام المنقول',
    'course.lesson28': 'الأفعال المركبة',
    'course.lesson29': 'مراجعة شاملة',
    'course.lesson30': 'اختبار تدريبي',
    'course.lesson31': 'الامتحان النهائي',
    'course.lesson32': 'منح الشهادة',
    
    // Branch names
    'branch.online': 'الفصول الافتراضية',
    'branch.onlineDesc': 'تعلم من أي مكان مع فصولنا الافتراضية',
    'branch.dammam': 'فرع الدمام',
    'branch.dammamDesc': 'الحرم الرئيسي في الدمام',
    'branch.dhahran': 'فرع الظهران',
    'branch.dhahranDesc': 'يقع في الظهران',
    'branch.khobar': 'فرع الخبر',
    'branch.khobarDesc': 'يقع في الخبر',
    
    // Payment methods
    'payment.card': 'بطاقة',
    'payment.cardDesc': 'بطاقة ائتمان/خصم - فيزا، ماستركارد، مدى',
    'payment.cash': 'كاش',
    'payment.cashDesc': 'ادفع نقداً في الفرع',
    'payment.cardCash': 'بطاقة/كاش',
    'payment.cardCashDesc': 'الدفع ببطاقة أو كاش',
    'payment.transfer': 'تحويل',
    'payment.transferDesc': 'تحويل بنكي مباشر',
    'payment.tamara': 'تمارا',
    'payment.tamaraDesc': 'قسّم على دفعات',
    'payment.tabby': 'تابي',
    'payment.tabbyDesc': 'اشترِ الآن وادفع لاحقاً',
    'payment.stcpay': 'اس تي سي باي',
    'payment.stcpayDesc': 'محفظة اس تي سي باي الرقمية',
    
    // Teacher Portal
    'teacher.login': 'تسجيل دخول المعلم',
    'teacher.email': 'البريد الإلكتروني للمعلم',
    'teacher.password': 'كلمة المرور',
    'teacher.loginButton': 'تسجيل الدخول إلى بوابة المعلم',
    'teacher.dashboard': 'لوحة المعلم',
    'teacher.backHome': 'العودة للرئيسية',
    'teacher.logout': 'تسجيل الخروج',
    'teacher.totalStudents': 'إجمالي الطلاب',
    'teacher.activeClasses': 'الفصول النشطة',
    'teacher.pendingAttendance': 'الحضور المعلق',
    'teacher.markAttendance': 'تسجيل الحضور',
    'teacher.uploadLessons': 'رفع الدروس',
    'teacher.createQuiz': 'إنشاء اختبار',
    'teacher.myStudents': 'طلابي',
    'teacher.course': 'الدورة',
    'teacher.progress': 'التقدم',
    'teacher.courseProgress': 'تقدم الدورة',
    'teacher.parts': 'أجزاء',
    'teacher.quizTitle': 'عنوان الاختبار',
    'teacher.quizTitlePlaceholder': 'أدخل عنوان الاختبار',
    'teacher.numberOfQuestions': 'عدد الأسئلة',
    'teacher.question': 'سؤال',
    'teacher.questionText': 'أدخل نص السؤال',
    'teacher.answers': 'خيارات الإجابة',
    'teacher.answer': 'إجابة',
    'teacher.addQuestion': 'إضافة سؤال',
    'teacher.saveQuiz': 'حفظ الاختبار',
    'teacher.quizCreated': 'تم إنشاء الاختبار بنجاح!',
    'teacher.quizCreatedDesc': 'تم إنشاء الاختبار الخاص بك',
    'teacher.questionType': 'نوع السؤال',
    'teacher.multipleChoice': 'اختيار من متعدد',
    'teacher.longAnswer': 'إجابة طويلة (مقال)',
    'teacher.imageQuestion': 'صورة',
    'teacher.videoQuestion': 'فيديو',
    'teacher.audioQuestion': 'صوت',
    'teacher.uploadFile': 'رفع ملف',
    'teacher.uploading': 'جاري الرفع...',
    'teacher.fileUploaded': 'تم رفع الملف',
    'teacher.removeFile': 'إزالة الملف',
    'teacher.correctAnswer': 'الإجابة الصحيحة',
    'teacher.markCorrect': 'تحديد كصحيح',
    'teacher.points': 'النقاط',
    'teacher.pointsPlaceholder': 'أدخل النقاط لهذا السؤال',
    'teacher.lessonTitle': 'عنوان الدرس',
    'teacher.lessonTitlePlaceholder': 'أدخل عنوان الدرس',
    'teacher.selectFile': 'اختر ملف',
    'teacher.selectedFile': 'الملف المحدد',
    'teacher.uploadLesson': 'رفع الدرس',
    'teacher.uploadedLessons': 'الدروس المرفوعة',
    'teacher.lessonUploaded': 'تم رفع الدرس بنجاح!',
    'teacher.lessonUploadedDesc': 'تم رفع الدرس',
    'teacher.error': 'خطأ',
    'teacher.fillAllFields': 'يرجى ملء جميع الحقول واختيار ملف',
    'teacher.studentName': 'اسم الطالب',
    'teacher.status': 'الحالة',
    'teacher.present': 'حاضر',
    'teacher.absent': 'غائب',
    'teacher.saveAttendance': 'حفظ الحضور',
    'teacher.attendanceSaved': 'تم حفظ الحضور بنجاح!',
    'teacher.attendanceSavedDesc': 'تم تسجيل الحضور',
    'teacher.loginError': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
    'teacher.loginSuccess': 'تم تسجيل دخول المعلم بنجاح!',
    'teacher.myQuizzes': 'اختباراتي',
    'teacher.viewQuizzes': 'عرض الاختبارات',
    'teacher.quizzes': 'الاختبارات',
    'teacher.attempts': 'المحاولات',
    'teacher.viewAttempts': 'عرض المحاولات',
    'teacher.noQuizzes': 'لم يتم إنشاء اختبارات بعد',
    'teacher.createFirstQuiz': 'إنشاء اختبارك الأول',
    'teacher.studentAnswers': 'إجابات الطلاب',
    'teacher.submittedAt': 'تم التسليم في',
    'teacher.notSubmitted': 'لم يتم التسليم',
    'teacher.viewDetails': 'عرض التفاصيل',
    'teacher.gradeQuiz': 'تقييم الاختبار',
    'teacher.graded': 'تم التقييم',
    'teacher.notGraded': 'لم يتم التقييم',
    'teacher.grade': 'الدرجة',
    'teacher.feedback': 'الملاحظات',
    'teacher.pointsAwarded': 'النقاط الممنوحة',
    'teacher.questionFeedback': 'ملاحظات السؤال',
    'teacher.saveGrade': 'حفظ التقييم',
    'teacher.gradedAt': 'تم التقييم في',
    'teacher.viewAllResults': 'عرض جميع نتائج الاختبارات',
    
    // Admin Portal
    'admin.login': 'بوابة الإدارة',
    'admin.email': 'البريد الإلكتروني للمسؤول',
    'admin.password': 'كلمة المرور',
    'admin.loginButton': 'تسجيل الدخول إلى بوابة الإدارة',
    'admin.secureAccess': 'وصول آمن للإدارة فقط. الوصول غير المصرح به محظور.',
    'admin.dashboard': 'لوحة الإدارة',
    'admin.backHome': 'العودة للرئيسية',
    'admin.logout': 'تسجيل الخروج',
    'admin.totalStudents': 'إجمالي الطلاب',
    'admin.totalTeachers': 'المعلمون النشطون',
    'admin.revenue': 'الإيرادات (ريال)',
    'admin.activeClasses': 'إكمال الدورة',
    'admin.studentsInfo': 'الطلاب',
    'admin.teachersInfo': 'المعلمون',
    'admin.recentRegistrations': 'التسجيلات الأخيرة',
    'admin.registeredOn': 'مسجل في',
    'admin.loginError': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
    'admin.loginSuccess': 'تم تسجيل دخول المسؤول بنجاح!',
    'admin.exportData': 'تصدير البيانات',
    'admin.nameEn': 'الاسم (إنجليزي)',
    'admin.nameAr': 'الاسم (عربي)',
    'admin.branch': 'الفرع',
    'admin.payment': 'الدفع',
    'admin.status': 'الحالة',
    'admin.assignedCourses': 'الدورات المعينة',
    'admin.students': 'طلاب',
    'admin.paymentManagement': 'إدارة المدفوعات',
    'admin.student': 'الطالب',
    'admin.amount': 'المبلغ (ريال)',
    'admin.date': 'التاريخ',
    'admin.paid': 'مدفوع',
    'admin.pending': 'معلق',
    'admin.analytics': 'التحليلات',
    'admin.reports': 'التقارير',
    'admin.analyticsInsights': 'التحليلات والرؤى',
    'admin.enrollmentTrend': 'اتجاه تسجيل الطلاب',
    'admin.studentPerformance': 'أداء الطلاب',
    'admin.reportsExport': 'التقارير والتصدير',
    'admin.studentDataReport': 'تقرير بيانات الطلاب',
    'admin.studentDataReportDesc': 'تصدير معلومات الطلاب الكاملة بما في ذلك الحضور والتقدم',
    'admin.exportCSV': 'تصدير CSV',
    'admin.paymentReport': 'تقرير الدفع',
    'admin.paymentReportDesc': 'تصدير سجل الدفع وتفاصيل المعاملات',
    'admin.exportPDF': 'تصدير PDF',
    'admin.teacherPerformanceReport': 'تقرير أداء المعلمين',
    'admin.teacherPerformanceReportDesc': 'تصدير إحصائيات المعلمين ونتائج الطلاب',
    'admin.analyticsSummary': 'ملخص التحليلات',
    'admin.analyticsSummaryDesc': 'تصدير تحليلات واتجاهات شاملة',
    'admin.exportSuccess': 'تم التصدير بنجاح!',
    'admin.exportSuccessDesc': 'تم تصدير البيانات عبر',
    'admin.shareToEmail': 'مشاركة عبر البريد الإلكتروني',
    'admin.downloadCSV': 'تحميل CSV',
    'admin.exportToGoogleDrive': 'تصدير إلى Google Drive',
    'admin.addNewStudent': 'إضافة طالب جديد',
    'admin.addPreviousStudents': 'إضافة طلاب سابقين',
    'admin.viewAttendanceRecords': 'عرض سجلات الحضور',
    
    // Student cards on homepage
    'home.studentLogin': 'تسجيل دخول الطالب',
    'home.studentLoginDesc': 'هل أنت مسجل بالفعل؟ قم بالوصول إلى مواد دورتك وتتبع تقدمك',
    'home.newStudentRegistration': 'تسجيل طالب جديد',
    'home.newStudentRegistrationDesc': 'أول مرة هنا؟ أكمل تسجيلك للانضمام إلى دوراتنا',
    'home.teacherLogin': 'تسجيل دخول المعلم',
    'home.teacherLoginDesc': 'قم بالوصول إلى لوحتك لإدارة الطلاب وتسجيل الحضور',
    'home.newTeacherRegistration': 'تسجيل معلم جديد',
    'home.newTeacherRegistrationDesc': 'انضم إلى فريقنا وابدأ في إدارة فصولك',
    'home.administration': 'الإدارة',
    
    // Add Previous Student Modal
    'addPrevStudent.title': 'إضافة طالب سابق',
    'addPrevStudent.step': 'خطوة',
    'addPrevStudent.of': 'من',
    'addPrevStudent.fullNameEn': 'الاسم الكامل (إنجليزي)',
    'addPrevStudent.fullNameAr': 'الاسم الكامل (عربي)',
    'addPrevStudent.phone1': 'هاتف 1',
    'addPrevStudent.phone2': 'هاتف 2 (اختياري)',
    'addPrevStudent.email': 'البريد الإلكتروني',
    'addPrevStudent.nationalId': 'رقم الهوية / الإقامة',
    'addPrevStudent.password': 'كلمة المرور',
    'addPrevStudent.passwordPlaceholder': 'ادخل كلمة المرور (6 أحرف على الأقل)',
    'addPrevStudent.selectCourses': 'اختر الدورات (يمكن اختيار عدة دورات)',
    'addPrevStudent.selected': 'تم اختيار',
    'addPrevStudent.courses': 'دورة',
    'addPrevStudent.selectBranch': 'اختر الفرع',
    'addPrevStudent.selectPaymentMethod': 'اختر طريقة الدفع',
    'addPrevStudent.addStudent': 'إضافة طالب',
    'addPrevStudent.fillAllFields': 'يرجى ملء جميع الحقول المطلوبة',
    'addPrevStudent.passwordMinLength': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    'addPrevStudent.selectAtLeastOneCourse': 'يرجى اختيار دورة واحدة على الأقل',
    'addPrevStudent.selectBranchError': 'يرجى اختيار فرع',
    'addPrevStudent.selectPaymentError': 'يرجى اختيار طريقة الدفع',
    'addPrevStudent.success': 'تم إضافة الطالب السابق بنجاح! جاري التحويل إلى صفحة الطالب...',
    'addPrevStudent.error': 'فشل في إضافة الطالب السابق',
    'addPrevStudent.generalError': 'حدث خطأ',
    
    // Common messages
    'common.loading': 'جاري التحميل...',
    'common.noStudentsYet': 'لا يوجد طلاب مسجلين بعد',
    'common.noTeachersYet': 'لا يوجد معلمون مسجلون بعد',
    'common.notAssigned': 'غير مخصص',
    
    // Student Quiz
    'student.availableQuizzes': 'الاختبارات المتاحة',
    'student.myQuizzes': 'اختباراتي',
    'student.takeQuiz': 'إجراء الاختبار',
    'student.quizCompleted': 'مكتمل',
    'student.quizNotStarted': 'لم يبدأ',
    'student.questions': 'الأسئلة',
    'student.totalPoints': 'إجمالي النقاط',
    'student.yourScore': 'نتيجتك',
    'student.submitQuiz': 'تسليم الاختبار',
    'student.selectAnswer': 'اختر إجابة',
    'student.writeAnswer': 'اكتب إجابتك هنا',
    'student.quizSubmitted': 'تم تسليم الاختبار!',
    'student.quizSubmittedDesc': 'تم تسليم إجاباتك بنجاح',
    'student.confirmSubmit': 'هل أنت متأكد من أنك تريد التسليم؟',
    'student.cannotChangeAnswers': 'لا يمكنك تغيير إجاباتك بعد التسليم',
    'student.studentAnswer': 'إجابة الطالب',
    'student.notes': 'الملاحظات',
    'student.myNotes': 'ملاحظاتي',
    'student.addNote': 'إضافة ملاحظة',
    'student.noteTitle': 'عنوان الملاحظة',
    'student.noteTitlePlaceholder': 'أدخل عنوان الملاحظة',
    'student.noteContent': 'محتوى الملاحظة',
    'student.noteContentPlaceholder': 'اكتب ملاحظاتك هنا...',
    'student.saveNote': 'حفظ الملاحظة',
    'student.editNote': 'تعديل الملاحظة',
    'student.deleteNote': 'حذف الملاحظة',
    'student.noNotes': 'لا توجد ملاحظات بعد',
    'student.createFirstNote': 'إنشاء ملاحظتك الأولى',
    'student.noteSaved': 'تم حفظ الملاحظة!',
    'student.noteSavedDesc': 'تم حفظ ملاحظتك بنجاح',
    'student.noteDeleted': 'تم حذف الملاحظة!',
    'student.noteDeletedDesc': 'تم حذف ملاحظتك',
    
    // Not Found
    'notfound.title': '404',
    'notfound.message': 'عذراً! الصفحة غير موجودة',
    'notfound.returnHome': 'العودة للصفحة الرئيسية',
    
    // Common
    'common.login': 'تسجيل الدخول',
    'common.signup': 'إنشاء حساب',
    'common.logout': 'تسجيل الخروج',
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.close': 'إغلاق',
    'common.created': 'تم الإنشاء',
    'common.back': 'رجوع',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    
    // Search and filters
    'search.studentsPlaceholder': 'البحث عن الطلاب بالاسم أو الهاتف أو الرقم التعريفي...',
    'search.teachersPlaceholder': 'البحث عن المعلمين بالاسم أو البريد الإلكتروني أو الدورات...',
    'search.studentManagementPlaceholder': 'البحث باسم الطالب أو رقم الهاتف أو الرقم التعريفي...',
    
    // Login placeholders
    'placeholder.adminEmail': 'admin@me-english.com',
    'placeholder.studentEmail': 'student@example.com',
    'placeholder.password': '••••••••',
    'placeholder.fullNameArabic': 'الاسم الكامل',
    'placeholder.fullNameEnglish': 'Full Name',
    'placeholder.phoneNumber': 'XXX XXX XXX',
    'placeholder.email': 'email@example.com',
    'placeholder.idNumber': 'ID Number',
    'placeholder.enterPassword': 'أدخل كلمة المرور (8 أحرف على الأقل)',
    'placeholder.teacherName': 'John Doe',
    'placeholder.grade': 'A+، B، 95%، إلخ.',
    'placeholder.courseDuration': 'أدخل عدد الأشهر',
    
    // Translation
    'translation.translating': 'جاري الترجمة من العربية...',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
